# -*- coding: utf-8 -*-
"""lvadsusr119-Sivaganes-Lab-2(Regression).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WhHkEWra0nTcxGeSJzCYohG9IKRBPeJA
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

data = pd.read_csv('/content/auto-mpg.csv')
df = pd.DataFrame(data)
df

df.isnull().sum()

data_fill = df.fillna(df.mean())
data_fill.isnull().sum()

data_fill['horsepower'] = data_fill['horsepower'].replace('?', np.nan)

data_fill['horsepower'] = pd.to_numeric(data_fill['horsepower'], errors='coerce')

data_fill['horsepower'].fillna(data_fill['horsepower'].mean(), inplace=True)

data_fill.isna().sum()

print(data_fill.describe())

print(data_fill.shape)

plt.figure(figsize=(10,8))
sns.boxplot(data=data_fill)
plt.title('Finding outliers')
plt.show()

q1 = data_fill.quantile(0.25)
q3 = data_fill.quantile(0.75)
iqr = q3 - q1

outliers = ((data_fill < (q1 - 1.5 * iqr)) | (data_fill > (q3 + 1.5 * iqr))).any(axis=1)
print(outliers)

cleaned_data = data[~outliers]
cleaned_data.shape

plt.figure(figsize=(10,8))
sns.boxplot(data=data_fill)
plt.title('After cleaning outliers')
plt.show()

data_fill.drop(columns=['car name'], inplace=True)

sns.histplot(data_fill['mpg'], kde=True)
plt.title('Distribution of Fuel Efficiency (mpg)')
plt.xlabel('mpg')
plt.ylabel('Frequency')
plt.show()

X = data_fill.drop('mpg', axis=1)
y = data_fill['mpg']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))